### ISSUE TITLE
Combinaison eau/terre => boue

### ISSUE THREAD

**Issue by KimiNako** [TeamConfiture/GWJ-43#17]
Passer à travers les grilles (vers le bas)

Si on est boue et on va dans l'eau, on meurt

Vitesse

Yellow + Blue

**Comment by watchinofoye** [comment]
Par eau + terre, vous voulez dire trèfle bleu + trèfle jaune ?
(ce serait bien de garder une certaine cohérence dans les noms des états et des couleurs)
