### ISSUE TITLE
Falling sound sometime not stopping

### ISSUE THREAD

**Issue by salty64** [TeamConfiture/GWJ-43#58]

**Comment by JohenSound** [comment]
Add Key stop on all Animation slime.
Bug fixed.

**Comment by JohenSound** [comment]
Le son va être géré autrement avec potentiellement un détachement de l'animation Player. Voir l'issue : https://github.com/TeamConfiture/GWJ-43/issues/127

**Comment by JohenSound** [comment]
Voir l'issue : https://github.com/TeamConfiture/GWJ-43/issues/127 résolu
